### ISSUE TITLE
Delegate this to AS112?

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dnsop-alt-tld#2]
Should .ALT be delegated to (new style) AS112 nameservers? 

We do suggest that caching and auth nameservers immediately return NXD for all names in .ALT, but until _everyone_ does that there will be some hitting the root.

**Comment by ggm-at-apnic** [comment]
As an exercise in exposing visibility, this adds value. As a mechanism tracking divergence from LSZ status, this might also be useful.
