### ISSUE TITLE
Should the IANA run a registry for this?

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dnsop-alt-tld#3]
Currently people generating alternate namespaces are just choosing one. We could ask the IANA to run an informational, first come, first served registry, or simply just mirror the existing behavior.

**Comment by ggm-at-apnic** [comment]
I think an informal registry is an oxymoron. Either there is a _cheap_ formalism, or there is a complex expensive formalism, but there has to be **formalism** if its a registry. 

I could imagine a tri-state flag: ```{uniquely-assigned, has-collisions, reserved, unique}```
