### ISSUE TITLE
Wholly responsible

### ISSUE THREAD

**Issue by paulehoffman** [wkumari/draft-wkumari-dnsop-alt-tld#32]
From the list, from @schanzen

"Developers are wholly responsible for dealing with any collisions"

I think this is an impossible task and as a developer that is addressed
here I have to say that we cannot do that unilaterally for our
implementation/design because collisions occur when _others_ do
something.
Maybe you are talking about "groups" (as used in this paragraph) or the
"alternative name system community" here, which would make more sense?
This paragraph also uses both "groups" and "developers", and the
difference (to me) is not clear.

Maybe simply strike this sentence again?
Instead or in addition maybe a full acknowledment of this issue in the
security considerations, along the lines of

"
This draft does not define a registry or governance model for the .alt
namespace and as such developers/groups as well as users and applications cannot
expect unambiguous mappings from names with a ".alt"-TLD to a specific
alternative name space / name resolution mechanism.
This issue can be mitigated, for example, through the creation and use of a
registry by the alternative name system developer community.
"

**Comment by wkumari** [comment]
Proposal: Combine these into one?

Something along the lines of: 
"The .alt namespace is unmanaged. This document does not define a registry or governance model for the .alt
namespace and so developers, applications and users should not expect unambiguous mappings from names to name resolution mechanisms. Mitigation or resolution of any collisions that may occur under .alt are outside the scope of this document, and outside the IETF's remit. Users are advised to consider the associated risks when using names under .alt."

This may still need some massaging (especially around 'namespace' and the different uses of the term 'Users')
