### ISSUE TITLE
Acknowledgments...

### ISSUE THREAD

**Issue by wkumari** [wkumari/draft-wkumari-dnsop-alt-tld#44]
Remember to add:
Barry Lieba

(I'm keeping this as an open issue for IETF LC comments)

**Comment by vcunat** [comment]
"Leiba", just to be sure.

**Comment by wkumari** [comment]
@vcunat Doh! Thank you! One day I"lll lean to tipe betthr!

**Comment by vcunat** [comment]
:-)  I assumed you just copied the typo from 71a979a8600e8a56d5160569936038ffd659130f

**Comment by paulehoffman** [comment]
Added for -23
