### ISSUE TITLE
Missing file CONTRIBUTING.md in the repo

### ISSUE THREAD

**Issue by pspacek** [wkumari/draft-wkumari-dnsop-alt-tld#5]
The very first like of README.md is
`Important: Read CONTRIBUTING.md before submitting feedback or contributing` but there is no `CONTRIBUTING.md` file in the repo.

**Comment by wkumari** [comment]
Wow, good catch. 
Thanks, I added it - I'll update it as the discussions about this evolve on the IETF list.
